#
# About: Test image for PICA object detection.
# Created by Shenyunbin at 14.04.2021
# Modified by Huanzhuo Wu at 23.07.2022
#

FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

ADD /.wheels/* /

RUN apt-get update && apt-get install -y \
        software-properties-common \
        net-tools iputils-ping iproute2 telnet sudo git wget zip \
        libsm6 libxext6 libfontconfig1 libxrender1 libgl1-mesa-glx
# Python3 requirements
# RUN add-apt-repository ppa:deadsnakes/ppa       
RUN apt-get install -y python3 python3-dev python3-pip 
RUN sudo apt-get install -y libsndfile1 ffmpeg
RUN pip3 install --default-timeout=1000 numpy==1.17.3
RUN pip3 install /scipy-1.8.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
RUN pip3 install --default-timeout=1000 scikit-learn==0.24.1
RUN pip3 install --default-timeout=1000 museval==0.2.0


WORKDIR /app/pICA-emu

USER root

CMD ["bash"]
