#!/bin/bash

# Install docker-ce instead of the docker in comnetsemu.
sudo apt-get update
sudo apt-get install -y apt-transport-https  ca-certificates curl  software-properties-common
curl -fsSL  https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add
sudo add-apt-repository "deb [arch=amd64]  https://download.docker.com/linux/ubuntu bionic stable" 
echo "Finish intalling docker11111"
sudo apt-get update
sudo apt-get install -y docker-ce
sudo groupadd docker
echo "Finish intalling docker22222"
sudo gpasswd -a vagrant docker
newgrp docker
echo "Finish intalling docker33333"

cd ~/comnetsemu/util
bash ./install.sh -u

echo "Finish updating dependencies"

# Build images for Docker hosts
cd /home/vagrant/comnetsemu/test_containers || exit
sudo bash ./build.sh