#
# About: Test image for PICA object detection.
# Created by Shenyunbin at 14.04.2021
#

FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
        software-properties-common \
        net-tools iputils-ping iproute2 telnet sudo git wget zip \
        libsm6 libxext6 libfontconfig1 libxrender1 libgl1-mesa-glx
# Python3 requirements
# RUN add-apt-repository ppa:deadsnakes/ppa       
RUN apt-get install -y python3 python3-dev python3-pip 
RUN sudo apt-get install -y libsndfile1 ffmpeg
RUN pip3 install numpy==1.15.0
RUN pip3 install scipy==0.19.0
RUN pip3 install scikit-learn==0.24.1
RUN pip3 install museval==0.2.0


WORKDIR /app/pICA-emu

USER root

CMD ["bash"]
